# 🎓 05. Underfitting/Overfitting Diagnostics & Final Conclusions
## Online Food Delivery Demand Forecasting & Peak Hour Regression Model
**Subject:** 602 – Data Analytics Using Python (DAP)  
**Group:** 6  

---
### 🎯 Objectives:
1. **Step 14:** Conduct rigorous Underfitting vs. Overfitting diagnostics by contrasting training and test performance across regression and classification models.
2. **Step 15:** Synthesize comprehensive business conclusions, operational recommendations for online food delivery platforms, model limitations, and future enhancements.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')
plt.rcParams['figure.autolayout'] = True

# Summary performance metrics calculated from pipeline
metrics_summary = pd.DataFrame({
    'Model': ['Multiple Linear Regression (Demand)', 'Logistic Regression (Peak Hour)'],
    'Target Variable': ['delivery_time_min (Continuous)', 'is_peak_hour (Binary 0/1)'],
    'Training Metric': ['R² = 0.5449 (MAE: 5.02 min)', 'Accuracy = 81.84%'],
    'Testing Metric': ['R² = 0.5480 (MAE: 5.00 min)', 'Accuracy = 81.66%'],
    'Generalization Gap': ['Delta R² = 0.0031', 'Delta Acc = 0.18%'],
    'Diagnostic Status': ['Optimal Generalization', 'Optimal Generalization']
})

display(metrics_summary)

,Model,Target Variable,Training Metric,Testing Metric,Generalization Gap,Diagnostic Status
0,Multiple Linear Regression (Demand),delivery_time_min (Continuous),R² = 0.5449 (MAE: 5.02 min),R² = 0.5480 (MAE: 5.00 min),Delta R² = 0.0031,Optimal Generalization
1,Logistic Regression (Peak Hour),is_peak_hour (Binary 0/1),Accuracy = 81.84%,Accuracy = 81.66%,Delta Acc = 0.18%,Optimal Generalization


### Step 14: Underfitting & Overfitting Diagnostics
#### Diagnostic Evaluation Criteria:
- **Overfitting (High Variance):** Would occur if the model scored very high on training data (e.g. $R^2 > 0.90$) but degraded significantly on test data (e.g. $R^2 < 0.40$).
- **Underfitting (High Bias):** Would occur if the model failed to capture data relationships on both training and testing sets equally ($R^2 < 0.10$).
- **Observed Finding:** 
  - Regression: Train $R^2 = 0.5449$ vs. Test $R^2 = 0.5480$ (Difference: $0.0031$).
  - Classification: Train Accuracy = $81.84\%$ vs. Test Accuracy = $81.66\%$ (Difference: $0.18\%$).
  - The near-identical performance on training and unseen testing partitions demonstrates high model stability and zero evidence of overfitting.

### Step 15: Conclusions & Business Insights

#### 1. Dataset & Operational Insights:
- **Dataset Size:** 45,593 verified food delivery orders across multiple metropolitan and urban delivery hubs.
- **Peak Demand Concentrations:** Over **65.5%** of all daily food delivery volume occurs within the lunch (12:00–14:00) and dinner (18:00–22:00) peak intervals.
- **Key Operational Bottlenecks:** Road traffic density (especially `Jam` conditions) is the largest operational factor increasing delivery delay (+14 minutes on average).

#### 2. Model Performance Summary:
- **Regression Forecasting:** Multiple Linear Regression accurately estimates order delivery duration with an MAE of **4.99 minutes** and $R^2 = 0.5480$.
- **Classification Accuracy:** Logistic Regression predicts peak hour demand state with **81.66% accuracy**.

#### 3. Actionable Business Recommendations:
1. **Dynamic Courier Fleet Pre-Allocation:** Pre-dispatch delivery personnel into high-demand restaurant clusters 30 minutes prior to dinner peak (17:30).
2. **Dynamic Surge Delivery Buffers:** Adjust customer ETA estimates upwards by 8–12 minutes during peak hours and heavy traffic alerts.
3. **Rider Routing Incentives:** Reward delivery partners for utilizing optimized routes and electric two-wheelers during heavy traffic windows.